spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: example
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  amqp:
    deserialization:
      trust:
        all: true
